import NextCors from "nextjs-cors";

export default async function handler(req, res) {
	await NextCors(req, res, {
		methods: ["GET"],
		origin: "*",
		optionsSuccessStatus: 200
	});
	res.status(200).json([
		{
			id: 1,
			boosts: 69,
			date_created: "2024-01-08T20:27:08.000Z",
			death_count: null,
			die_reason: 2,
			duration: 2039,
			flags: null,
			flappycombo: 13,
			gamemode_id: 1,
			kill_count: 39,
			killer_level: 103,
			killer_name: null,
			killer_user_id: null,
			level: 52,
			max_leaderboard: 1,
			name: null,
			room_id: null,
			score: 4041843,
			team_id: null,
			time_to_last: null,
			user_id: 5,
			won: null,
			coins_earned: 63,
			killer_tribe_id: null,
			killer_tribe_name: null,
			victim_tribe_id: null,
			victim_tribe_name: null
		},
		{
			id: 2,
			boosts: 69,
			date_created: "2024-01-08T08:28:52.000Z",
			death_count: null,
			die_reason: 2,
			duration: 8079,
			flags: null,
			flappycombo: 0,
			gamemode_id: 1,
			kill_count: 192,
			killer_level: 117,
			killer_name: null,
			killer_user_id: null,
			level: 52,
			max_leaderboard: 1,
			name: null,
			room_id: null,
			score: 10029794,
			team_id: null,
			time_to_last: null,
			user_id: 5,
			won: null,
			coins_earned: 181,
			killer_tribe_id: null,
			killer_tribe_name: null,
			victim_tribe_id: null,
			victim_tribe_name: null
		},
		{
			id: 3,
			boosts: 69,
			date_created: "2024-01-08T05:57:09.000Z",
			death_count: null,
			die_reason: 2,
			duration: 396,
			flags: null,
			flappycombo: 1,
			gamemode_id: 1,
			kill_count: 3,
			killer_level: 98,
			killer_name: null,
			killer_user_id: null,
			level: 52,
			max_leaderboard: 2,
			name: null,
			room_id: null,
			score: 900961,
			team_id: null,
			time_to_last: null,
			user_id: 5,
			won: null,
			coins_earned: 12,
			killer_tribe_id: null,
			killer_tribe_name: null,
			victim_tribe_id: null,
			victim_tribe_name: null
		},
		{
			id: 4,
			boosts: 69,
			date_created: "2024-01-08T05:50:31.000Z",
			death_count: null,
			die_reason: 2,
			duration: 14,
			flags: null,
			flappycombo: 0,
			gamemode_id: 1,
			kill_count: 0,
			killer_level: 113,
			killer_name: null,
			killer_user_id: null,
			level: 52,
			max_leaderboard: null,
			name: null,
			room_id: null,
			score: 400,
			team_id: null,
			time_to_last: null,
			user_id: 5,
			won: null,
			coins_earned: 0,
			killer_tribe_id: null,
			killer_tribe_name: null,
			victim_tribe_id: null,
			victim_tribe_name: null
		},
		{
			id: 5,
			boosts: 69,
			date_created: "2024-01-08T05:50:13.000Z",
			death_count: null,
			die_reason: 2,
			duration: 230,
			flags: null,
			flappycombo: 0,
			gamemode_id: 1,
			kill_count: 5,
			killer_level: 119,
			killer_name: null,
			killer_user_id: null,
			level: 52,
			max_leaderboard: 3,
			name: null,
			room_id: null,
			score: 822139,
			team_id: null,
			time_to_last: null,
			user_id: 5,
			won: null,
			coins_earned: 12,
			killer_tribe_id: null,
			killer_tribe_name: null,
			victim_tribe_id: null,
			victim_tribe_name: null
		}
	]);
}
